### ISSUE TITLE
link not working on README.md page

### ISSUE THREAD

**Issue by farhan7reza7** [RakibHassan01/imdb_nextJS#1]
link not working on README.md page

error:

![image](https://github.com/RakibHassan01/imdb_nextJS/assets/108195448/a45d56db-84ed-470d-8167-3bbabc1860b6)

update [ README.md documentation here](https://github.com/RakibHassan01/imdb_nextJS/blob/main/README.md)

**Comment by justrakibhassan** [comment]
- Updated the live site URL in the README.md file
